# -*- coding: utf-8 -*-
"""Copia de gastos compra-venta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fcLI6miR_N3HNYeuBJFmTwA_BH156R-D
"""

# -*- coding: utf-8 -*-
# Cálculo de gastos de operación: Venta en CABA y Compra en PBA
# Los valores de cierre los ingresa el usuario

# -----------------------------
# VENTA CABA
# -----------------------------
valor_cierre_caba = float(input("Ingrese el valor de cierre de la propiedad en CABA (USD): "))

# Porcentajes de gastos (según planilla)
honorarios_inmobiliaria_caba = 0.03      # 3%
imp_sellos_caba = 0.0175                 # 1.75%
iti_caba = 0.015                         # 1.5%
gastos_escribania_caba = 0.005           # 0.5%

# Cálculo de cada gasto
comision_caba = valor_cierre_caba * honorarios_inmobiliaria_caba
sellos_caba = valor_cierre_caba * imp_sellos_caba
iti_caba_monto = valor_cierre_caba * iti_caba
escribania_caba = valor_cierre_caba * gastos_escribania_caba

# Total de gastos y neto
gastos_totales_caba = comision_caba + sellos_caba + iti_caba_monto + escribania_caba
importe_neto_venta_caba = valor_cierre_caba - gastos_totales_caba


# -----------------------------
# COMPRA PBA
# -----------------------------
valor_cierre_pba = float(input("Ingrese el valor de cierre de la propiedad en PBA (USD): "))

# Porcentajes de gastos (según planilla)
honorarios_inmobiliaria_pba = 0.04       # 4%
imp_sellos_pba = 0.01                    # 1%
honorarios_escribano_pba = 0.01          # 1%
gastos_escribania_pba = 0.005            # 0.5%

# Cálculo de cada gasto
comision_pba = valor_cierre_pba * honorarios_inmobiliaria_pba
sellos_pba = valor_cierre_pba * imp_sellos_pba
honorarios_escribano_pba_monto = valor_cierre_pba * honorarios_escribano_pba
escribania_pba = valor_cierre_pba * gastos_escribania_pba

# Total de gastos y total compra
gastos_totales_pba = comision_pba + sellos_pba + honorarios_escribano_pba_monto + escribania_pba
importe_total_compra_pba = valor_cierre_pba + gastos_totales_pba


# -----------------------------
# CÁLCULOS ADICIONALES
# -----------------------------
dinero_necesario = importe_total_compra_pba - importe_neto_venta_caba
disponible_talia = float(input("Ingrese el dinero disponible de Talia (USD): "))
disponible_manu = float(input("Ingrese el dinero disponible de Manu (USD): "))
disponible_total = disponible_talia + disponible_manu

# -----------------------------
# RESULTADOS
# -----------------------------
print("\n=== RESULTADOS OPERACIÓN ===\n")

# --- Venta en CABA ---
print(f"🟦 Venta en CABA - Valor cierre: U$S {valor_cierre_caba:,.2f}")
print("Desglose de gastos:")
print(f"      • Comisión inmobiliaria (3%):        U$S {comision_caba:,.2f}")
print(f"      • Impuesto a Sellos (1.75%):         U$S {sellos_caba:,.2f}")
print(f"      • ITI (1.5%):                        U$S {iti_caba_monto:,.2f}")
print(f"      • Escribanía (0.5%):                 U$S {escribania_caba:,.2f}")
print(f"  ➜ Total gastos venta CABA:              U$S {gastos_totales_caba:,.2f}")
print(f"\033[91m\033[1m  ➜ Importe neto de la venta:             U$S {importe_neto_venta_caba:,.2f}\033[0m\n") # Formatted

# --- Compra en PBA ---
print(f"🟩 Compra en PBA - Valor cierre: U$S {valor_cierre_pba:,.2f}")
print("Desglose de gastos:")
print(f"      • Comisión inmobiliaria (4%):        U$S {comision_pba:,.2f}")
print(f"      • Impuesto a Sellos (1%):            U$S {sellos_pba:,.2f}")
print(f"      • Honorarios Escribano (1%):         U$S {honorarios_escribano_pba_monto:,.2f}")
print(f"      • Gastos Escribanía (0.5%):          U$S {escribania_pba:,.2f}")
print(f"  ➜ Total gastos compra PBA:              U$S {gastos_totales_pba:,.2f}")
print(f"\033[91m\033[1m  ➜ Importe total de la compra:           U$S {importe_total_compra_pba:,.2f}\033[0m\n") # Formatted

# --- Balance final ---
print("=== BALANCE FINAL ===")
print(f"Dinero necesario para completar la compra: U$S {dinero_necesario:,.2f}")
print(f"Dinero disponible de Talia:                U$S {disponible_talia:,.2f}")
print(f"Dinero disponible de Manu:                 U$S {disponible_manu:,.2f}")
print(f"Total disponible:                          U$S {disponible_total:,.2f}")

faltante = disponible_total - dinero_necesario
if faltante >= 0:
    print(f"✅ Sobrante después de aportes:            U$S {faltante:,.2f}")
else:
    print(f"\033[91m\033[1m⚠️  A pedir con el crédito:                U$S {-faltante:,.2f}\033[0m") # Formatted